### ISSUE TITLE
Different results using BacktestTool and Gekko UI

### ISSUE THREAD

**Issue by bruno-berchielli** [xFFFFF/Gekko-BacktestTool#11]
Hello,

I'm getting slightly different results with Gekko UI and BacktestTool with:
- The same strategy
- Same pair and dataset interval 
- Default TOML file (I've hardcoded the settings) 
- same paper trader settings

The results are pretty close (even upon lookin on the "Roundtrips" table, but are not the same. Not sure if this is to be expected.  

[backtest-config.txt](https://github.com/xFFFFF/Gekko-BacktestTool/files/1958674/backtest-config.txt)
[gekko-backtest-tool-output.txt](https://github.com/xFFFFF/Gekko-BacktestTool/files/1958670/gekko-backtest-tool-output.txt)
[Gekko-result-ui.pdf](https://github.com/xFFFFF/Gekko-BacktestTool/files/1958671/Gekko-result-ui.pdf)

**Comment by xFFFFF** [comment]
Probably values for currency and asset amount (see below), slippage or fee are not identical for UI and BacktesTool.

At present, the amount of currency and asset for backtests is hardcoded. You can change them by editing the backtest.pl file in a text editor on the line 365, 366
https://github.com/xFFFFF/Gekko-BacktestTool/blob/b06fb59827cdc65fc4d80b6bb90508824ea40306/backtest.pl

The value for slippage, fee taker and fee maker can be set in the configuration file backtest-config.pl. In the next version, I will fix in next version that the amount of currency and asset is also set in this file.

To check or change values for UI, open gekko/config/plugins/paperTrader.toml file.
