### ISSUE TITLE
Error when trying to import data

### ISSUE THREAD

**Issue by bettimms** [xFFFFF/Gekko-BacktestTool#13]
Running any of these commands results on error below

`perl backtest.pl -i -f 2017-04-20 -t now` or
`perl backtest.pl -i -p binance:BTC:ALL -f last -t now`

**_`Can't locate object method "new" via package "JSON" at backtest.pl line 447.`_**

Tried on Windows machine and MacOS!

**Comment by xFFFFF** [comment]
Its fixed wih #8 in open source version. I will recompile binaries today.
