### ISSUE TITLE
Search for best parameter when it is a string 

### ISSUE THREAD

**Issue by bruno-berchielli** [xFFFFF/Gekko-BacktestTool#14]
Hello,

I'm trying to run the neuralnet strat and it has several possible parameters for the "training method" that are defined as a string; 

> // the neural network training method to use. Options are 'sgd', 'adagrad', 'windowgrad', 'nesterov'
> method = 'adadelta'

I want to use BacktestTool to search several parameters combinations, including the "method".

When I try to set my TOML file as: 

`method = " 'adagrad', 'sgd', 'adagrad', 'windowgrad', 'nesterov', 'adadelta' "
`
**Result**:  Nothing happens 

`method = 'adagrad', 'sgd', 'adagrad', 'windowgrad', 'nesterov', 'adadelta'`

or

`method = adagrad, sgd, adagrad, windowgrad, nesterov, adadelta`

**Result**: Syntax error (expected) 

Thanks

**Comment by xFFFFF** [comment]
Check: `method = " \'adagrad\', \'sgd\', \'adagrad\', \'windowgrad\', \'nesterov\', \'adadelta\' "`
Im not sure if your example with spaces before/after double quote will work. Double quote will should add automatically. This is needed to successfully parse data from the TOML file to Perl. Then the string between the double quote is replaced by regular expression.

I know that the Github version has a bug associated with this syntax of BF. Once you run backtest, you can make sure that all the options have been processed correctly, you can enable keep_logs in backtest-config.pl and check the files created in the log folder. The file includes config.js content from gekko.
