### ISSUE TITLE
Brute force does not work ?

### ISSUE THREAD

**Issue by xaviermiss** [xFFFFF/Gekko-BacktestTool#18]
Hi,

Thank you for this tool ! :-)

I am trying to find thes best parameters of a strategy.
I modified the TOML file and launch the tool.
It computes something during one minute, creates the csv file, puts the colomn titles in it and stop the process.
I tried either:
 - by erasing the TOML file -> it directly tells me that it did not find the TOML file (juste to validate it searches the file)
 - with the start..end:step
 - with the start.end:step
 - with the specific values (value1, value2, value3, ...) I want it to compute with (12 variables with 10 values each one)

I specified the "$debug = 'yes';" option but no error/debug output.

Is this feature working ?

Thank you in advance
Xavier

**Comment by xFFFFF** [comment]
Have you splited datasets? Breaks between periods? If so, do not use the scan mode, but manually enter the date for these datasets. It's a bug that can improve one day.

**Comment by xaviermiss** [comment]
Hi xFFFFF

You were right.
I drastically decreased the number of configurations (from billionns to hundreds of thousands) and it works !

Thank you
Xavier
