### ISSUE TITLE
Importer working yet?

### ISSUE THREAD

**Issue by thegamecat** [xFFFFF/Gekko-BacktestTool#4]
Really liking this script!

Does the importer exist ?

/mnt/f/bash/g511/gekko$ perl backtest.pl -i
Can't open perl script "backtest.pl": No such file or directory
:/mnt/f/bash/g511/gekko$ cd GekkoBacktestTool/
/mnt/f/bash/g511/gekko/GekkoBacktestTool$ perl backtest.pl -i
Failed to change directory to 'util/genMarketFiles': No such file or directory at backtest.pl line 257.
:/mnt/f/bash/g511/gekko/GekkoBacktestTool$ perl backtest.pl -i
Updating Gekko's poloniex market data...
module.js:472
    throw err;
    ^

Error: Cannot find module '/mnt/f/bash/g511/gekko/GekkoBacktestTool/util/genMarketFiles/update-poloniex.js'

**Comment by bitoutshop** [comment]
This is still an issue, Only for binance
Everything works fine when importing from Poloniex, but as soon as I add in a Binance pair to the backtest_config.pl  it gets this error.

**Comment by deba10106** [comment]
I get this error for binance data import!. 

"Failed to change directory to 'util/genMarketFiles': No such file or directory at script/backtest.pl line 489."
Anyone has any solution?

**Comment by sahni619** [comment]
Even I am getting the same issue. Do we have a solution for this ?
