### ISSUE TITLE
Save strategy props in csv file

### ISSUE THREAD

**Issue by bettimms** [xFFFFF/Gekko-BacktestTool#6]
How to enable to save strategy properties in .csv file just like in the GIF in README?

**Comment by xFFFFF** [comment]
Because of the bug, I had to temporarily disable this feature, but it will return in the next version, which will push on Github today or tomorrow.

**Comment by xFFFFF** [comment]
New version (with strats config in CSV output) is available on repo.

**Comment by bettimms** [comment]
I'm getting NA for strategy settings?!
<img width="318" alt="na_strategy_settings" src="https://user-images.githubusercontent.com/9863453/39392941-f632c6c0-4acf-11e8-87a3-f9c3879d21c1.png">

**Comment by xFFFFF** [comment]
Check new version. Should work.

**Comment by bettimms** [comment]
Yes it works now! Just as a suggestion, maybe to leave it in configuration to save it as `JSON` since when we add as strategy in `config.js` it should be as `JS` object.
Anyway thank you for this great tool!

**Comment by xFFFFF** [comment]
I will remember your suggestion as option for the next versions. Thanks for feedback :)
