### ISSUE TITLE
Winbash / WSL issue | Solved. 

### ISSUE THREAD

**Issue by thegamecat** [xFFFFF/Gekko-BacktestTool#7]
Not entirely sure if this is anything you can resolve or have ideas on but worth documenting anyway.

When running backtest.pl - config is correct etc what we get is:
Can't exec "node": No such file or directory at backtest.pl line 624.

I THINK this is winbash causing perl to run in "Windows" and not "WSL". Not clear yet though.

**Comment by thegamecat** [comment]
Interestingly while paths are correct I have to explicitly put the full path to node in the backtest.pl. Now some other errors need fixing!

**Comment by thegamecat** [comment]
Looks to me like it's working now.

**Comment by xFFFFF** [comment]
I didnt try start BacktestTool in Winbash. I checked only on raw Windows (cmd.exe) with Strawberry Perl. I will look closely at the problem over the next few days. Thanks for feedback.
